// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// 빌드 시(Vercel 등) DATABASE_URL이 없어도 prisma generate는 통과합니다.
// 런타임에는 Vercel 환경 변수에 DATABASE_URL을 반드시 설정하세요.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: (process.env.DATABASE_URL ?? "") as string,
  },
});
