# -*- coding: utf-8 -*-
import json, os

BASE = os.path.join(os.path.dirname(__file__), '..', 'messages')

PATCHES = {
  "ja": {
    "FAQ": {
      "q1": "アップロードできるファイル形式は？",
      "a1": "EPUBMakerはDOCX（Word）、TXT、PDF、HTML、Markdown（.md）に対応しています。すべて標準のEPUB 3またはEPUB 2に変換されます。",
      "q2": "ファイル変換にアカウントは必要ですか？",
      "a2": "いいえ。基本的な変換はアカウントなしでご利用いただけます。変換履歴を保存したい場合は、無料アカウントを作成してください。",
      "q3": "ファイルサイズに制限はありますか？",
      "a3": "ファイルは50MB以下、表紙画像は10MB以下でご利用ください。ほとんどの原稿はこの範囲に収まります。",
      "q4": "EPUBのバージョンはどちらを選べばよいですか？",
      "a4": "EPUB 3をおすすめします。リッチメディア、高品質なタイポグラフィ、最新のリーダーアプリに対応しています。旧型端末向けの場合のみEPUB 2をお選びください。",
      "q5": "目次が表示されないのはなぜですか？",
      "a5": "DOCXファイルの目次は、見出しスタイルから自動生成されます。太字テキストではなく、Wordの組み込み見出しスタイル（見出し1・2・3）をご使用ください。",
      "q6": "表紙画像の推奨サイズは？",
      "a6": "Amazon Kindleは2,560×1,600px、Apple Booksは1,400×2,100pxを推奨しています。どの環境でも使える汎用サイズは1,600×2,400pxです。",
      "q7": "変換後に目次を編集できますか？",
      "a7": "はい。変換後、内蔵の目次エディタで章の並べ替え・名前変更・インデント調整・削除が行えます。ダウンロード前に自由にカスタマイズできます。",
      "q8": "EPUBMakerはずっと無料ですか？",
      "a8": "はい。EPUBMakerは変換回数無制限の無料ツールです。控えめな広告によって運営されています。"
    },
    "TocEditor": {
      "title": "目次エディタ",
      "loading": "目次を読み込み中…",
      "noNavTitle": "目次エディタ",
      "noNavDesc": "このEPUBには編集可能な目次がありません。",
      "noNavHint": "Pandocで変換した場合は、目次生成オプションを有効にして再変換してください。",
      "close": "閉じる",
      "errorTitle": "目次エディタエラー",
      "instructions": "ドラッグで並べ替え · クリックで名前変更 · ← / → でインデント調整",
      "empty": "目次の項目がありません。",
      "dragHandle": "ドラッグして移動",
      "outdent": "インデントを下げる",
      "indent": "インデントを上げる",
      "clickToEdit": "クリックして名前変更",
      "noLabel": "（タイトルなし）",
      "addItem": "+ 項目を追加",
      "newChapter": "新しいチャプター",
      "saving": "保存中…",
      "saveAndDownload": "保存してダウンロード",
      "reset": "リセット"
    },
    "ConversionList": {
      "empty": "変換履歴がありません。",
      "expired": "期限切れ",
      "expiresInDays": "{days}日後に期限切れ",
      "expiresInHours": "{hours}時間後に期限切れ",
      "fileExpired": "ファイルが期限切れです",
      "downloadError": "ファイルを読み込めませんでした。",
      "download": "ダウンロード",
      "editToc": "目次を編集"
    },
    "FileUpload": {
      "errorTextLength": "ファイルが長すぎます（現在{current}文字）。テキストファイルは最大{max}文字です。",
      "openTocEditor": "目次エディタを開く",
      "ariaUpload": "DOCX、TXT、PDF、HTMLまたはMDファイルをアップロード",
      "chooseFile": "ファイルを選択"
    }
  },
  "es": {
    "FAQ": {
      "q1": "¿Qué formatos de archivo puedo subir?",
      "a1": "EPUBMaker admite archivos DOCX (Word), TXT, PDF, HTML y Markdown (.md). Todos se convierten en EPUB 3 o EPUB 2 estándar.",
      "q2": "¿Necesito una cuenta para convertir archivos?",
      "a2": "No. La conversión básica funciona sin cuenta. Si quieres guardar tu historial de conversiones, crea una cuenta gratuita.",
      "q3": "¿Hay un límite de tamaño de archivo?",
      "a3": "Los archivos deben ser de 50 MB o menos, y las imágenes de portada de 10 MB o menos.",
      "q4": "¿Qué versión de EPUB debo elegir?",
      "a4": "Recomendamos EPUB 3: admite contenido multimedia, mejor tipografía y las apps de lectura más modernas. Usa EPUB 2 solo para dispositivos más antiguos.",
      "q5": "¿Por qué no aparece mi tabla de contenidos?",
      "a5": "En archivos DOCX, la tabla de contenidos se genera a partir de los estilos de título. Asegúrate de usar los estilos de encabezado integrados de Word, no texto en negrita.",
      "q6": "¿Qué dimensiones de portada funcionan mejor?",
      "a6": "Amazon Kindle recomienda 2.560 × 1.600 px. Apple Books recomienda 1.400 × 2.100 px. Un tamaño seguro y universal es 1.600 × 2.400 px.",
      "q7": "¿Puedo editar la tabla de contenidos tras la conversión?",
      "a7": "Sí. Usa el editor de índice integrado para reordenar, renombrar o eliminar capítulos antes de descargar.",
      "q8": "¿EPUBMaker es gratuito para siempre?",
      "a8": "Sí. EPUBMaker es una herramienta gratuita sin límite de conversiones, mantenida con publicidad discreta."
    },
    "TocEditor": {
      "title": "Editor de índice",
      "loading": "Cargando tabla de contenidos…",
      "noNavTitle": "Editor de índice",
      "noNavDesc": "Este EPUB no tiene una tabla de contenidos editable.",
      "noNavHint": "Si convertiste con Pandoc, activa la generación de índice y vuelve a convertir.",
      "close": "Cerrar",
      "errorTitle": "Error en el editor de índice",
      "instructions": "Arrastra para reordenar · Clic para renombrar · ← / → para ajustar sangría",
      "empty": "No hay elementos en la tabla de contenidos.",
      "dragHandle": "Arrastra para mover",
      "outdent": "Disminuir sangría",
      "indent": "Aumentar sangría",
      "clickToEdit": "Clic para renombrar",
      "noLabel": "(sin título)",
      "addItem": "+ Añadir elemento",
      "newChapter": "Nuevo capítulo",
      "saving": "Guardando…",
      "saveAndDownload": "Guardar y descargar",
      "reset": "Restablecer"
    },
    "ConversionList": {
      "empty": "No hay historial de conversiones.",
      "expired": "Caducado",
      "expiresInDays": "Caduca en {days} días",
      "expiresInHours": "Caduca en {hours} horas",
      "fileExpired": "Archivo caducado",
      "downloadError": "No se pudo cargar el archivo.",
      "download": "Descargar",
      "editToc": "Editar índice"
    },
    "FileUpload": {
      "dropText": "Arrastra tu archivo aquí",
      "dropHere": "Soltar aquí",
      "browse": "o haz clic para buscar — {extensions}",
      "uploadedFile": "Archivo subido",
      "removeFile": "Eliminar archivo",
      "convertButton": "Convertir a EPUB",
      "converting": "Convirtiendo…",
      "errorConversionFailed": "La conversión falló.",
      "errorFileType": "Solo se admiten archivos DOCX o TXT. \"{name}\" no está soportado.",
      "errorFileSize": "El archivo debe ser de 50 MB o menos.",
      "errorCoverSize": "La imagen de portada debe ser de 10 MB o menos.",
      "batchTitle": "Conversión por lotes",
      "batchHint": "Selecciona varios archivos para convertirlos a la vez.",
      "convertAll": "Convertir todos a EPUB",
      "convertingBatch": "Convirtiendo {current} de {total}…",
      "downloadAllZip": "Descargar todo en ZIP",
      "downloadFile": "Descargar",
      "uploadFile": "Subir archivo",
      "recentLabel": "Proyectos recientes",
      "importGoogleDocs": "Importar desde Google Docs",
      "importNotion": "Importar desde Notion",
      "notionUrlPlaceholder": "Pega la URL de la página de Notion…",
      "notionImportButton": "Importar",
      "notionImporting": "Importando…",
      "notionError": "No se pudo cargar la página de Notion. Verifica la URL y que la página esté compartida con la integración.",
      "errorTextLength": "El archivo es demasiado largo ({current} caracteres). El límite para archivos de texto es {max} caracteres.",
      "openTocEditor": "Abrir editor de índice",
      "ariaUpload": "Subir archivo DOCX, TXT, PDF, HTML o MD",
      "chooseFile": "Elegir archivo"
    }
  },
  "de": {
    "FAQ": {
      "q1": "Welche Dateiformate kann ich hochladen?",
      "a1": "EPUBMaker unterstützt DOCX (Word), TXT, PDF, HTML und Markdown (.md). Alle werden in Standard-EPUB 3 oder EPUB 2 konvertiert.",
      "q2": "Brauche ich ein Konto zum Konvertieren?",
      "a2": "Nein. Die Grundfunktion ist ohne Konto nutzbar. Für den Zugriff auf die Konvertierungshistorie genügt ein kostenloses Konto.",
      "q3": "Gibt es eine Dateigrößenbeschränkung?",
      "a3": "Dateien dürfen maximal 50 MB, Coverbilder maximal 10 MB groß sein.",
      "q4": "Welche EPUB-Version soll ich wählen?",
      "a4": "EPUB 3 wird empfohlen – es unterstützt Rich Media, bessere Typografie und moderne Lese-Apps. EPUB 2 nur für ältere Geräte.",
      "q5": "Warum wird mein Inhaltsverzeichnis nicht angezeigt?",
      "a5": "Bei DOCX-Dateien wird das Inhaltsverzeichnis aus Überschriften-Stilen generiert. Verwende die integrierten Überschriften-Stile von Word, nicht manuell fett formatierten Text.",
      "q6": "Welche Bildgröße eignet sich für das Cover?",
      "a6": "Amazon Kindle empfiehlt 2.560 × 1.600 px. Apple Books empfiehlt 1.400 × 2.100 px. Eine universelle Standardgröße ist 1.600 × 2.400 px.",
      "q7": "Kann ich das Inhaltsverzeichnis nach der Konvertierung bearbeiten?",
      "a7": "Ja. Im integrierten Inhaltsverzeichnis-Editor kannst du Kapitel neu anordnen, umbenennen oder löschen.",
      "q8": "Ist EPUBMaker dauerhaft kostenlos?",
      "a8": "Ja. EPUBMaker ist ein kostenloses Tool ohne Konvertierungslimit, finanziert durch dezente Werbung."
    },
    "TocEditor": {
      "title": "Inhaltsverzeichnis-Editor",
      "loading": "Inhaltsverzeichnis wird geladen…",
      "noNavTitle": "Inhaltsverzeichnis-Editor",
      "noNavDesc": "Dieses EPUB hat kein bearbeitbares Inhaltsverzeichnis.",
      "noNavHint": "Falls mit Pandoc konvertiert, aktiviere die Inhaltsverzeichnis-Generierung und konvertiere erneut.",
      "close": "Schließen",
      "errorTitle": "Fehler im Inhaltsverzeichnis-Editor",
      "instructions": "Ziehen zum Sortieren · Klicken zum Umbenennen · ← / → für Einzug",
      "empty": "Keine Einträge im Inhaltsverzeichnis.",
      "dragHandle": "Ziehen zum Verschieben",
      "outdent": "Einzug verringern",
      "indent": "Einzug erhöhen",
      "clickToEdit": "Klicken zum Umbenennen",
      "noLabel": "(kein Titel)",
      "addItem": "+ Eintrag hinzufügen",
      "newChapter": "Neues Kapitel",
      "saving": "Wird gespeichert…",
      "saveAndDownload": "Speichern & Herunterladen",
      "reset": "Zurücksetzen"
    },
    "ConversionList": {
      "empty": "Keine Konvertierungshistorie.",
      "expired": "Abgelaufen",
      "expiresInDays": "Läuft in {days} Tagen ab",
      "expiresInHours": "Läuft in {hours} Stunden ab",
      "fileExpired": "Datei abgelaufen",
      "downloadError": "Datei konnte nicht geladen werden.",
      "download": "Herunterladen",
      "editToc": "Inhaltsverzeichnis bearbeiten"
    },
    "FileUpload": {
      "dropText": "Datei hier ablegen",
      "dropHere": "Hier ablegen",
      "browse": "oder klicken zum Auswählen — {extensions}",
      "uploadedFile": "Hochgeladene Datei",
      "removeFile": "Datei entfernen",
      "convertButton": "In EPUB konvertieren",
      "converting": "Wird konvertiert…",
      "errorConversionFailed": "Konvertierung fehlgeschlagen.",
      "errorFileType": "Nur DOCX- oder TXT-Dateien sind zulässig. \"{name}\" wird nicht unterstützt.",
      "errorFileSize": "Die Datei darf maximal 50 MB groß sein.",
      "errorCoverSize": "Das Coverbild darf maximal 10 MB groß sein.",
      "batchTitle": "Stapelkonvertierung",
      "batchHint": "Wähle mehrere Dateien für die gleichzeitige Konvertierung aus.",
      "convertAll": "Alle in EPUB konvertieren",
      "convertingBatch": "Konvertierung {current} von {total}…",
      "downloadAllZip": "Alle als ZIP herunterladen",
      "downloadFile": "Herunterladen",
      "uploadFile": "Datei hochladen",
      "recentLabel": "Letzte Projekte",
      "importGoogleDocs": "Aus Google Docs importieren",
      "importNotion": "Aus Notion importieren",
      "notionUrlPlaceholder": "Notion-Seiten-URL einfügen…",
      "notionImportButton": "Importieren",
      "notionImporting": "Wird importiert…",
      "notionError": "Die Notion-Seite konnte nicht geladen werden. Überprüfe die URL und ob die Seite mit der Integration geteilt wurde.",
      "errorTextLength": "Die Datei ist zu lang ({current} Zeichen). Textdateien sind auf {max} Zeichen begrenzt.",
      "openTocEditor": "Inhaltsverzeichnis-Editor öffnen",
      "ariaUpload": "DOCX-, TXT-, PDF-, HTML- oder MD-Datei hochladen",
      "chooseFile": "Datei auswählen"
    }
  },
  "zh": {
    "FAQ": {
      "q1": "我可以上传哪些文件格式？",
      "a1": "EPUBMaker支持DOCX（Word）、TXT、PDF、HTML和Markdown（.md）文件，均可转换为标准EPUB 3或EPUB 2格式。",
      "q2": "转换文件需要注册账号吗？",
      "a2": "不需要。基础转换功能无需账号即可使用。如需保存转换记录，注册免费账号即可。",
      "q3": "文件大小有限制吗？",
      "a3": "文件大小不得超过50MB，封面图片不得超过10MB。大多数书稿都在此范围内。",
      "q4": "应该选择哪个EPUB版本？",
      "a4": "推荐使用EPUB 3，支持富媒体、更优质的排版和现代阅读应用。仅在兼容旧设备时使用EPUB 2。",
      "q5": "为什么我的目录没有显示？",
      "a5": "DOCX文件的目录由标题样式自动生成。请确保使用Word内置标题样式（标题1、2、3等），而非手动加粗的文字。",
      "q6": "封面图片的最佳尺寸是多少？",
      "a6": "Amazon Kindle推荐2560×1600像素，Apple Books推荐1400×2100像素，通用安全尺寸为1600×2400像素。",
      "q7": "转换后可以编辑目录吗？",
      "a7": "可以。转换完成后，使用内置目录编辑器对章节进行排序、重命名或删除，下载前随时调整。",
      "q8": "EPUBMaker永远免费吗？",
      "a8": "是的。EPUBMaker是一款无转换次数限制的免费工具，通过非侵入性广告维持运营。"
    },
    "TocEditor": {
      "title": "目录编辑器",
      "loading": "正在加载目录…",
      "noNavTitle": "目录编辑器",
      "noNavDesc": "此EPUB没有可编辑的目录。",
      "noNavHint": "如果使用Pandoc转换，请启用目录生成选项后重新转换。",
      "close": "关闭",
      "errorTitle": "目录编辑器错误",
      "instructions": "拖拽排序 · 点击重命名 · ← / → 调整层级",
      "empty": "目录中没有条目。",
      "dragHandle": "拖拽移动",
      "outdent": "减少缩进",
      "indent": "增加缩进",
      "clickToEdit": "点击重命名",
      "noLabel": "（无标题）",
      "addItem": "+ 添加条目",
      "newChapter": "新章节",
      "saving": "正在保存…",
      "saveAndDownload": "保存并下载",
      "reset": "重置"
    },
    "ConversionList": {
      "empty": "暂无转换记录。",
      "expired": "已过期",
      "expiresInDays": "{days}天后过期",
      "expiresInHours": "{hours}小时后过期",
      "fileExpired": "文件已过期",
      "downloadError": "文件加载失败。",
      "download": "下载",
      "editToc": "编辑目录"
    },
    "FileUpload": {
      "dropText": "将文件拖拽到此处",
      "dropHere": "放置于此",
      "browse": "或点击选择 — {extensions}",
      "uploadedFile": "已上传文件",
      "removeFile": "删除文件",
      "convertButton": "转换为EPUB",
      "converting": "转换中…",
      "errorConversionFailed": "转换失败。",
      "errorFileType": "仅支持DOCX或TXT文件。不支持\"{name}\"。",
      "errorFileSize": "文件大小不得超过50MB。",
      "errorCoverSize": "封面图片大小不得超过10MB。",
      "batchTitle": "批量转换",
      "batchHint": "选择多个文件一次性完成转换。",
      "convertAll": "全部转换为EPUB",
      "convertingBatch": "正在转换 {current} / {total}…",
      "downloadAllZip": "全部打包下载（ZIP）",
      "downloadFile": "下载",
      "uploadFile": "上传文件",
      "recentLabel": "最近项目",
      "importGoogleDocs": "从Google Docs导入",
      "importNotion": "从Notion导入",
      "notionUrlPlaceholder": "粘贴Notion页面URL…",
      "notionImportButton": "导入",
      "notionImporting": "导入中…",
      "notionError": "无法加载Notion页面，请检查URL，并确认页面已与集成共享。",
      "errorTextLength": "文件过长（当前{current}字）。文本文件最多支持{max}字。",
      "openTocEditor": "打开目录编辑器",
      "ariaUpload": "上传DOCX、TXT、PDF、HTML或MD文件",
      "chooseFile": "选择文件"
    }
  },
  "fr": {
    "FAQ": {
      "q1": "Quels formats de fichiers puis-je importer ?",
      "a1": "EPUBMaker prend en charge les fichiers DOCX (Word), TXT, PDF, HTML et Markdown (.md). Ils sont tous convertis en EPUB 3 ou EPUB 2 standard.",
      "q2": "Ai-je besoin d'un compte pour convertir des fichiers ?",
      "a2": "Non. La conversion de base fonctionne sans compte. Créez un compte gratuit si vous souhaitez conserver votre historique de conversions.",
      "q3": "Y a-t-il une limite de taille de fichier ?",
      "a3": "Les fichiers doivent faire 50 Mo maximum. Les images de couverture doivent faire 10 Mo maximum.",
      "q4": "Quelle version d'EPUB dois-je choisir ?",
      "a4": "L'EPUB 3 est recommandé : il prend en charge les médias enrichis, une meilleure typographie et les applications de lecture modernes. Utilisez l'EPUB 2 uniquement pour les appareils anciens.",
      "q5": "Pourquoi ma table des matières n'apparaît-elle pas ?",
      "a5": "Pour les fichiers DOCX, la table des matières est générée à partir des styles de titre. Utilisez les styles de titre intégrés de Word, et non du texte mis en gras manuellement.",
      "q6": "Quelles dimensions sont recommandées pour la couverture ?",
      "a6": "Amazon Kindle recommande 2 560 × 1 600 px. Apple Books recommande 1 400 × 2 100 px. Une taille universelle sûre est 1 600 × 2 400 px.",
      "q7": "Puis-je modifier la table des matières après la conversion ?",
      "a7": "Oui. Utilisez l'éditeur de table des matières intégré pour réorganiser, renommer ou supprimer des chapitres avant de télécharger.",
      "q8": "EPUBMaker est-il gratuit pour toujours ?",
      "a8": "Oui. EPUBMaker est un outil gratuit sans limite de conversions, soutenu par une publicité discrète."
    },
    "TocEditor": {
      "title": "Éditeur de table des matières",
      "loading": "Chargement de la table des matières…",
      "noNavTitle": "Éditeur de table des matières",
      "noNavDesc": "Cet EPUB ne possède pas de table des matières modifiable.",
      "noNavHint": "Si converti avec Pandoc, activez la génération de table des matières et reconvertissez.",
      "close": "Fermer",
      "errorTitle": "Erreur de l'éditeur",
      "instructions": "Glisser pour réorganiser · Cliquer pour renommer · ← / → pour l'indentation",
      "empty": "Aucun élément dans la table des matières.",
      "dragHandle": "Glisser pour déplacer",
      "outdent": "Réduire le retrait",
      "indent": "Augmenter le retrait",
      "clickToEdit": "Cliquer pour renommer",
      "noLabel": "(sans titre)",
      "addItem": "+ Ajouter un élément",
      "newChapter": "Nouveau chapitre",
      "saving": "Enregistrement…",
      "saveAndDownload": "Enregistrer et télécharger",
      "reset": "Réinitialiser"
    },
    "ConversionList": {
      "empty": "Aucun historique de conversion.",
      "expired": "Expiré",
      "expiresInDays": "Expire dans {days} jours",
      "expiresInHours": "Expire dans {hours} heures",
      "fileExpired": "Fichier expiré",
      "downloadError": "Impossible de charger le fichier.",
      "download": "Télécharger",
      "editToc": "Modifier la table des matières"
    },
    "FileUpload": {
      "dropText": "Déposez votre fichier ici",
      "dropHere": "Déposer ici",
      "browse": "ou cliquez pour parcourir — {extensions}",
      "uploadedFile": "Fichier importé",
      "removeFile": "Supprimer le fichier",
      "convertButton": "Convertir en EPUB",
      "converting": "Conversion en cours…",
      "errorConversionFailed": "La conversion a échoué.",
      "errorFileType": "Seuls les fichiers DOCX ou TXT sont acceptés. « {name} » n'est pas pris en charge.",
      "errorFileSize": "Le fichier doit faire 50 Mo ou moins.",
      "errorCoverSize": "L'image de couverture doit faire 10 Mo ou moins.",
      "batchTitle": "Conversion par lot",
      "batchHint": "Sélectionnez plusieurs fichiers pour les convertir en une seule fois.",
      "convertAll": "Tout convertir en EPUB",
      "convertingBatch": "Conversion {current} sur {total}…",
      "downloadAllZip": "Tout télécharger en ZIP",
      "downloadFile": "Télécharger",
      "uploadFile": "Importer un fichier",
      "recentLabel": "Projets récents",
      "importGoogleDocs": "Importer depuis Google Docs",
      "importNotion": "Importer depuis Notion",
      "notionUrlPlaceholder": "Coller l'URL de la page Notion…",
      "notionImportButton": "Importer",
      "notionImporting": "Importation…",
      "notionError": "Impossible de charger la page Notion. Vérifiez l'URL et que la page est partagée avec l'intégration.",
      "errorTextLength": "Le fichier est trop long ({current} caractères). Les fichiers texte sont limités à {max} caractères.",
      "openTocEditor": "Ouvrir l'éditeur de table des matières",
      "ariaUpload": "Importer un fichier DOCX, TXT, PDF, HTML ou MD",
      "chooseFile": "Choisir un fichier"
    }
  },
  "pt": {
    "FAQ": {
      "q1": "Quais formatos de arquivo posso enviar?",
      "a1": "O EPUBMaker suporta arquivos DOCX (Word), TXT, PDF, HTML e Markdown (.md). Todos são convertidos para EPUB 3 ou EPUB 2 padrão.",
      "q2": "Preciso de uma conta para converter arquivos?",
      "a2": "Não. A conversão básica funciona sem conta. Crie uma conta gratuita se quiser salvar seu histórico de conversões.",
      "q3": "Há limite de tamanho de arquivo?",
      "a3": "Os arquivos devem ter no máximo 50 MB. As imagens de capa devem ter no máximo 10 MB.",
      "q4": "Qual versão do EPUB devo escolher?",
      "a4": "O EPUB 3 é recomendado — suporta mídia rica, melhor tipografia e apps de leitura modernos. Use o EPUB 2 apenas para dispositivos mais antigos.",
      "q5": "Por que meu sumário não aparece?",
      "a5": "Em arquivos DOCX, o sumário é gerado a partir dos estilos de título. Use os estilos de título integrados do Word, não texto em negrito manual.",
      "q6": "Quais dimensões de capa funcionam melhor?",
      "a6": "Amazon Kindle recomenda 2.560 × 1.600 px. Apple Books recomenda 1.400 × 2.100 px. Um tamanho seguro e universal é 1.600 × 2.400 px.",
      "q7": "Posso editar o sumário após a conversão?",
      "a7": "Sim. Use o editor de sumário integrado para reorganizar, renomear ou excluir capítulos antes de baixar.",
      "q8": "O EPUBMaker é gratuito para sempre?",
      "a8": "Sim. O EPUBMaker é uma ferramenta gratuita sem limite de conversões, mantida por publicidade discreta."
    },
    "TocEditor": {
      "title": "Editor de sumário",
      "loading": "Carregando sumário…",
      "noNavTitle": "Editor de sumário",
      "noNavDesc": "Este EPUB não possui um sumário editável.",
      "noNavHint": "Se convertido com Pandoc, ative a geração de sumário e reconverta.",
      "close": "Fechar",
      "errorTitle": "Erro no editor de sumário",
      "instructions": "Arraste para reordenar · Clique para renomear · ← / → para ajustar recuo",
      "empty": "Nenhum item no sumário.",
      "dragHandle": "Arrastar para mover",
      "outdent": "Diminuir recuo",
      "indent": "Aumentar recuo",
      "clickToEdit": "Clique para renomear",
      "noLabel": "(sem título)",
      "addItem": "+ Adicionar item",
      "newChapter": "Novo capítulo",
      "saving": "Salvando…",
      "saveAndDownload": "Salvar e baixar",
      "reset": "Redefinir"
    },
    "ConversionList": {
      "empty": "Nenhum histórico de conversões.",
      "expired": "Expirado",
      "expiresInDays": "Expira em {days} dias",
      "expiresInHours": "Expira em {hours} horas",
      "fileExpired": "Arquivo expirado",
      "downloadError": "Não foi possível carregar o arquivo.",
      "download": "Baixar",
      "editToc": "Editar sumário"
    },
    "FileUpload": {
      "dropText": "Arraste seu arquivo aqui",
      "dropHere": "Soltar aqui",
      "browse": "ou clique para procurar — {extensions}",
      "uploadedFile": "Arquivo enviado",
      "removeFile": "Remover arquivo",
      "convertButton": "Converter para EPUB",
      "converting": "Convertendo…",
      "errorConversionFailed": "A conversão falhou.",
      "errorFileType": "Apenas arquivos DOCX ou TXT são aceitos. \"{name}\" não é suportado.",
      "errorFileSize": "O arquivo deve ter no máximo 50 MB.",
      "errorCoverSize": "A imagem de capa deve ter no máximo 10 MB.",
      "batchTitle": "Conversão em lote",
      "batchHint": "Selecione vários arquivos para converter de uma vez.",
      "convertAll": "Converter todos para EPUB",
      "convertingBatch": "Convertendo {current} de {total}…",
      "downloadAllZip": "Baixar tudo em ZIP",
      "downloadFile": "Baixar",
      "uploadFile": "Enviar arquivo",
      "recentLabel": "Projetos recentes",
      "importGoogleDocs": "Importar do Google Docs",
      "importNotion": "Importar do Notion",
      "notionUrlPlaceholder": "Cole a URL da página do Notion…",
      "notionImportButton": "Importar",
      "notionImporting": "Importando…",
      "notionError": "Não foi possível carregar a página do Notion. Verifique a URL e se a página está compartilhada com a integração.",
      "errorTextLength": "O arquivo é muito longo ({current} caracteres). Arquivos de texto têm limite de {max} caracteres.",
      "openTocEditor": "Abrir editor de sumário",
      "ariaUpload": "Enviar arquivo DOCX, TXT, PDF, HTML ou MD",
      "chooseFile": "Escolher arquivo"
    }
  }
}

def deep_merge(base, patch):
    for k, v in patch.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            deep_merge(base[k], v)
        else:
            base[k] = v

for locale, patch in PATCHES.items():
    path = os.path.join(BASE, f"{locale}.json")
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    deep_merge(data, patch)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  updated {locale}.json")

print("Done.")
